name: Waka Readme
on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  pull_request: {branches: ["master", "main"]}
  schedule:
    # Runs at 12am IST
    # - cron: '30 18 * * *'

    # Runs every 2 hours
    - cron: "0 */2 * * *"
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          COMMIT_BY_ME: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "True"
          SHOW_SHORT_INFO: "True"
